<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="Config.fs" />
        <Compile Include="CommandLine.fs" />
        <Compile Include="Program.fs" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\SDCard\SDCard.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="System.Text.Json" Version="8.0.4" />
    </ItemGroup>

</Project>
